# Generated by Django 6.0.4 on 2026-05-27 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nazionalita', models.CharField(blank=True, max_length=150, null=True)),
                ('biografia', models.TextField()),
                ('data_debutto', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artisti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genere',
                'verbose_name_plural': 'Generi',
                'ordering': ['titolo'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('anno', models.IntegerField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.artista')),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.genere')),
            ],
            options={
                'ordering': ['titolo'],
            },
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('durata_secondi', models.IntegerField()),
                ('traccia', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
            options={
                'verbose_name': 'Canzone',
                'verbose_name_plural': 'Canzoni',
                'ordering': ['titolo'],
            },
        ),
    ]
