# Generated by Django 6.0.4 on 2026-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
