# Generated by Django 6.0.4 on 2026-05-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_disponibile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['titolo', '-anno']},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nome', '-data_debutto'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artisti'},
        ),
        migrations.AlterModelOptions(
            name='canzone',
            options={'ordering': ['traccia', 'titolo'], 'verbose_name': 'Canzone', 'verbose_name_plural': 'Canzoni'},
        ),
    ]
