# Generated by Django 6.0.4 on 2026-05-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_options_alter_artista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Album', to='music.artista'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Album', to='music.genere'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titolo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='canzone',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Canzone', to='music.album'),
        ),
        migrations.AlterField(
            model_name='genere',
            name='titolo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
