# Generated by Django 6.0.4 on 2026-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_artista_alter_album_genere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['titolo'],
            },
        ),
        migrations.AlterField(
            model_name='artista',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canzone',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='canzoni', to='music.tag'),
        ),
    ]
