services:
  django-demo:
    build: .
    container_name: django-demo
    command: python manage.py runserver 0.0.0.0:8000 # Standard
    # command: daphne -b 0.0.0.0 -p 8000 config.asgi:application # websockets
    volumes:
      - .:/app
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=config.settings
    stdin_open: true
    tty: true

  library-frontend:
    build:
      context: .
      dockerfile: dockerfile-frontend
    container_name: library-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true