# Generated by Django 6.0.4 on 2026-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utente',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='utente',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='libri_prestito',
            field=models.ManyToManyField(to='catalogo.risorsa'),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='titolo',
            field=models.CharField(max_length=100),
        ),
    ]
