# Generated by Django 6.0.4 on 2026-05-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risorsa',
            options={'ordering': ['titolo']},
        ),
    ]
