# Generated by Django 6.0.4 on 2026-06-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_risorsa_utente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risorsa',
            options={'ordering': ['titolo'], 'verbose_name': 'Risorsa', 'verbose_name_plural': 'Risorse'},
        ),
    ]
