# Generated by Django 6.0.4 on 2026-06-05 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_utente_options_utente_attivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='risorsa',
            name='utenti_prestito',
            field=models.ManyToManyField(blank=True, related_name='libri_prestito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
