# Generated by Django 6.0.4 on 2026-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_risorsa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='risorsa',
            name='autore_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
