# Generated by Django 6.0.4 on 2026-05-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esercitazione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='prodotti',
        ),
        migrations.AddField(
            model_name='ordine',
            name='prodotto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='esercitazione.prodotto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='quantita',
            field=models.IntegerField(default=1),
        ),
    ]
