# Generated by Django 6.0.4 on 2026-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esercitazione', '0002_remove_ordine_prodotti_ordine_prodotto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('localita', models.ManyToManyField(to='esercitazione.localita')),
            ],
        ),
    ]
